use_frameworks!

platform :ios, '9.0'

target 'ActivityIndicatorOverlayView_Example' do
  pod 'ActivityIndicatorOverlayView', :path => '../'

  target 'ActivityIndicatorOverlayView_Tests' do
    inherit! :search_paths

    
  end
end
